package com.formulaire;
import com.classes.Passenger;
import com.classes.Reservation;
import com.gestion.GestionReservation;
import com.formulaire.form.Form;
import javax.swing.JOptionPane;
import com.gestion.GestionPassenger;
import java.time.LocalDateTime;
import com.gestion.GestionTicket;
import com.gestion.TrainTicketReferenceGenerator;
import com.classes.Ticket;
import java.util.List;
import java.util.ArrayList;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;

/**
 *
 * @author Djenidi
 */
public class RegisterPassenger extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPassenger
     */
    public RegisterPassenger() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        labelPlace.setText("Place choisi : " + com.gestion.ValuePassed.listToString());
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); 
        
        name.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField tf = (JTextField) input;
                String text = tf.getText();
                if (text.length() <= 1 || !Form.Name(text))
                {
                    JOptionPane.showMessageDialog(input, "Le champs doit être rempli correctement sans chiffre ou des caractères spéciaux et doit contenir au moins deux lettres!");
                    return false;
                }
                return true; // valide, on laisse passer
            }
        });
        
        firstName.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField tf = (JTextField) input;
                String text = tf.getText();
                if (text.length() <= 1 || !Form.Name(text))
                {
                    JOptionPane.showMessageDialog(input, "Le champs doit être rempli correctement sans chiffre ou des caractères spéciaux et doit contenir au moins deux lettres!");
                    return false;
                }
                return true; // valide, on laisse passer
            }
        });
        
        phone.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField tf = (JTextField) input;
                String text = tf.getText();
                if (!Form.PhoneNumberValid(text))
                {
                    JOptionPane.showMessageDialog(input, "Votre numéro de téléphone n'est pas valide!\nPour un numéro de téléphone valide, voici un exemple +26137XXXXXXX!");
                    return false;
                }
                return true; // valide, on laisse passer
            }
        });
        
        email.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField tf = (JTextField) input;
                String text = tf.getText();
                if (!Form.Email(text))
                {
                    JOptionPane.showMessageDialog(input, "Votre email est incorecte!\nPour un email correcte voici un exemple example@gmail.com!");
                    return false;
                } else if (!GestionPassenger.emailExist(text))
                {
                    JOptionPane.showMessageDialog(input, "Cette email existe déjà!\nVeuilliez entrer un autre email!");
                    return false;
                }
                return true; // valide, on laisse passer
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        labelPlace = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(8, 103, 136));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(8, 103, 136), 1, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(379, 462));

        jLabel26.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Réservation de place");

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });

        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });

        firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameKeyReleased(evt);
            }
        });

        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nom");

        jLabel28.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Prenom");

        jLabel29.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Phone");

        jLabel30.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("email");

        jButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton.setText("Réserver");
        jButton.setPreferredSize(new java.awt.Dimension(189, 39));
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        labelPlace.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        labelPlace.setForeground(new java.awt.Color(255, 255, 255));
        labelPlace.setText("Place : A1, B2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(labelPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(97, 97, 97))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel26)
                .addGap(39, 39, 39)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(12, 12, 12)
                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(9, 9, 9)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPlace)
                .addGap(21, 21, 21)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nameValue = (String)name.getText();
        String firstNameValue = (String)firstName.getText();
        String phoneValue = (String)phone.getText();
        String emailValue = (String)email.getText();
        boolean valid = Form.Passenger(nameValue, firstNameValue, phoneValue, emailValue) == 0;
        boolean emailValid = Form.Email(emailValue);
        boolean phoneValid = Form.PhoneNumberValid(phoneValue);

        if(valid && emailValid && phoneValid && GestionPassenger.emailExist(emailValue))
        {
            int route = 2;
            try
            {
                Passenger pass = new Passenger(0, nameValue, firstNameValue,emailValue, phoneValue);
                GestionPassenger gestPass = new GestionPassenger();
                int id = gestPass.insert(pass);
                Reservation res = new Reservation(id, route, com.gestion.ValuePassed.idPlace, LocalDateTime.now());
                GestionReservation gestRes = new GestionReservation();
                gestRes.reserverPlace(res);
                int i = 0;
                List<Ticket> listTicket = new ArrayList<>();
                while(i < com.gestion.ValuePassed.idPlace.size())
                {
                    String reference = TrainTicketReferenceGenerator.generateReference("PAR", "MAD");
                    Ticket ticket = new Ticket(reference, route, reference + "qrG", id, com.gestion.ValuePassed.idPlace.get(i));
                    listTicket.add(ticket);
                    i++;
                }
                GestionTicket gestTicket = new GestionTicket();
                gestTicket.insertMultiple(listTicket);
                
                JOptionPane.showMessageDialog(this, "Enregistrement reussite");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Erreur : " + e.getMessage());
            }
        }
        else if(!valid)
        {
            JOptionPane.showMessageDialog(this, "Veuilliez remplir tous les champs possibles!");
        }
        else if(valid && !emailValid && phoneValid && GestionPassenger.emailExist(emailValue))
        {
            JOptionPane.showMessageDialog(this, "Votre email est incorecte!\nPour un email correcte voici un exemple example@gmail.com!");
        }
        else if(!GestionPassenger.emailExist(emailValue))
        {
            JOptionPane.showMessageDialog(this, "Cette email existe déjà!\nVeuilliez entrer un autre email!");
        }
        else if(valid && emailValid && !phoneValid)
        {
            JOptionPane.showMessageDialog(this, "Votre numéro de téléphone n'est pas valide!\nPour un numéro de téléphone valide, voici un exemple +26137XXXXXXX!");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        boolean value  = Form.Name(name.getText());
        if (!value)
        {
            JOptionPane.showMessageDialog(this, "Le champs doit être rempli correctement sans chiffre ou des caractères spéciaux et doit contenir au moins deux lettres!");
        }
    }//GEN-LAST:event_nameKeyReleased

    private void firstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyReleased
        boolean value = Form.Name(firstName.getText());
        if (!value)
        {
            JOptionPane.showMessageDialog(this, "Le champs doit être rempli correctement sans chiffre ou des caractères spéciaux et doit contenir au moins deux lettres!");
        }
    }//GEN-LAST:event_firstNameKeyReleased

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        boolean value = Form.PhoneNumberValid(phone.getText());
        if (!value)
        {
            JOptionPane.showMessageDialog(this, "Votre numéro de téléphone n'est pas valide!\nPour un numéro de téléphone valide, voici un exemple +26137XXXXXXX!");        
        }
    }//GEN-LAST:event_phoneKeyReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        boolean emailValid = Form.Email(email.getText());
        if(!emailValid)
        {
            JOptionPane.showMessageDialog(this, "Votre email est incorecte!\nPour un email correcte voici un exemple example@gmail.com!");
        }
    }//GEN-LAST:event_emailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPassenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelPlace;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
